# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04a67076b89f606b2170c180aadedb6a9205385a4d021dc61dd68764ba5f7f4f5d4a46aaa5afb25983d9c4aa4c04c05e2bb42e6eb219c0eb070dcece7df4b56b

test:
  secret_key_base: e62830153bed6ef439c62a6bc48d046f897c904f4e945b8b90d143fe34705029b928fe1f35266ae114d2e1d3e807a9cefb12f45fcfb992b230380f56b73c0f3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
